name = "cf-workers-github-releases"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

# uncomment and adjust following if you are not using GitHub Actions
# kv_namespaces = [{binding="KV_GITHUB_RELEASES", id="xxxx"}]

[triggers]
crons = ["0 * * * *"]
